apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: flink
deploy:
  helm:
    releases:
    - name: flink
      remoteChart: https://downloads.apache.org/flink/flink-kubernetes-operator-1.11.0/
      namespace: mainflame
      createNamespace: true
# portForward:
# - resourceType: service
#   resourceName: grafana
#   namespace: mainflame
#   address: 0.0.0.0
#   port: 3000
#   localPort: 3000
